// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW607qrEFBSpxbws-SKip5Lw4ZQYAbPa8',
    appId: '1:782102620471:web:fcd2a48cb271faa5a8d2b2',
    messagingSenderId: '782102620471',
    projectId: 'warp-chats',
    authDomain: 'warp-chats.firebaseapp.com',
    storageBucket: 'warp-chats.firebasestorage.app',
    measurementId: 'G-N3LYJYS06Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSJ6CJPC3CPY5nkL_oWhJQjL4Ve4w0CDs',
    appId: '1:782102620471:android:eeca95202b7ebac1a8d2b2',
    messagingSenderId: '782102620471',
    projectId: 'warp-chats',
    storageBucket: 'warp-chats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-h6A0CTSH-0HkbYBIeUH3g8IybXDyNxw',
    appId: '1:782102620471:ios:28d45374ec18986aa8d2b2',
    messagingSenderId: '782102620471',
    projectId: 'warp-chats',
    storageBucket: 'warp-chats.firebasestorage.app',
    iosClientId: '782102620471-05ike24769fij2iaaapa2lgnj9ijthnc.apps.googleusercontent.com',
    iosBundleId: 'id.thedev.jay.warpchats.warpChats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-h6A0CTSH-0HkbYBIeUH3g8IybXDyNxw',
    appId: '1:782102620471:ios:28d45374ec18986aa8d2b2',
    messagingSenderId: '782102620471',
    projectId: 'warp-chats',
    storageBucket: 'warp-chats.firebasestorage.app',
    iosClientId: '782102620471-05ike24769fij2iaaapa2lgnj9ijthnc.apps.googleusercontent.com',
    iosBundleId: 'id.thedev.jay.warpchats.warpChats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW607qrEFBSpxbws-SKip5Lw4ZQYAbPa8',
    appId: '1:782102620471:web:4a723c635bbb2679a8d2b2',
    messagingSenderId: '782102620471',
    projectId: 'warp-chats',
    authDomain: 'warp-chats.firebaseapp.com',
    storageBucket: 'warp-chats.firebasestorage.app',
    measurementId: 'G-1V9EGF1DF5',
  );
}
